# Args: <path_to_bop_data> <bop_datset_name> <bop_toolkit_path> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py",
      "scikit-image",
      "pypng==0.0.20",
      "scipy==1.2.2",
      "matplotlib==2.2.4"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:3>",
          "sys_paths": ["<args:2>"] # path to the bop toolkit
        }
      }
    },
    {
      "module": "loader.BopLoader",
      "config": {
        "bop_dataset_path": "<args:0>/<args:1>",
        "mm2m": True,
        "split": "val",
        "obj_ids": [6],
        "model_type": ""
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000
          }
        ]
      }
    },
    {
      "module": "camera.CameraSampler",
      "config": {
        "cam_poses": [
          {
            "number_of_samples": 1,
            "location": {
              "provider":"sampler.Sphere",
              "center":[0, 0, 0],
              "radius": 0.4,
              "mode": "SURFACE"
            },
            "rotation": {
              "format": "look_at",
              "value": {
                "provider": "getter.POI"
              }
            }
          }
        ]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "transparent_background": False,
        "render_normals": True,
        "samples": 350,
        "render_distance": True
      }
    },
    {
      "module": "writer.ShapeNetWriter"
    },
    {
      "module": "writer.CameraStateWriter",
      "config": {
        "attributes_to_write": ["location", "rotation_euler", "fov_x", "fov_y", "shift_x", "shift_y", "cam_K", "cam2world_matrix"]
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "write_alpha_channel": False,
        "postprocessing_modules": {
          "distance": [
            {
              "module": "postprocessing.Dist2Depth",
              "config": {}
            }
          ]
        }
      }
    },
    {
      "module": "writer.BopWriter",
      "config": {
        "dataset": "<args:1>",
        "append_to_existing_output": True,
        "depth_scale": 1.0,
        "postprocessing_modules": {
          "distance": [
            {"module": "postprocessing.Dist2Depth"}
          ]
        }
      }
    }
  ]
}